### ISSUE TITLE
The "linux" folder doesn't exists

### ISSUE THREAD

**Issue by Spl3en** [icon-project/rewardcalculator#9]
https://github.com/icon-project/rewardcalculator/blob/b9d3326cf67edbe5bb5e940a6700020c839554e4/Makefile#L9

When installing the rc_icon tool with `make install` on linux, it fails because the `linux` folder doesn't exists.

**Comment by eunsoo-icon** [comment]
If you want to install on linux, execute following commands.
```bash
$ make linux
$ make install
```

I plan to modify Makefile for this inconvenient structure.
```bash
$ make  # detect OS and compile tools for detected OS
$ make darwin  # compile tools for OS X
$ make linux  # compile tools for linux
$ make install # install tools for detected OS
```

**Comment by Spl3en** [comment]
Oh, that makes totally sense now. Thanks for the clarification 👍

**Comment by eunsoo-icon** [comment]
> If you want to install on linux, execute following commands.
> 
> ```shell
> $ make linux
> $ make install
> ```
> 
> I plan to modify Makefile for this inconvenient structure.
> 
> ```shell
> $ make  # detect OS and compile tools for detected OS
> $ make darwin  # compile tools for OS X
> $ make linux  # compile tools for linux
> $ make install # install tools for detected OS
> ```

modify `$ make install # install compiled tools on system`
